# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=25)),
                ('workout_desc', models.CharField(max_length=250)),
                ('reps', models.PositiveIntegerField(default=1)),
                ('sets', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
